import { kanbanItemType } from "./components/kanban/KanbanList";
import { taskType } from "./components/tasks/TaskCart";
import { SidebarMenuItemsType } from "./types";

export const sidebarMenuItems: SidebarMenuItemsType = [
  {
    id: 1,
    title: "Overview",
    items: [
      {
        id: 1,
        title: "dashboard",
        icon: "/icons/dashboard.svg",
        path: "dashboard",
      },
      {
        id: 2,
        title: "projects",
        icon: "/icons/projects.svg",
        path: "projects",
      },
      {
        id: 3,
        title: "reports",
        icon: "/icons/projects.svg",
        path: "reports",
      },
    ],
  },
  {
    id: 2,
    title: "navigation",
    items: [
      {
        id: 1,
        title: "updates",
        icon: "/icons/updates.svg",
        path: "updates",
      },
      {
        id: 2,
        title: "management",
        icon: "/icons/management.svg",
        path: "management",
      },
      {
        id: 3,
        title: "kanban Desk",
        icon: "/icons/kanban_desk.svg",
        path: "kanban_desk",
      },
      {
        id: 4,
        title: "tasks",
        icon: "/icons/tasks.svg",
        path: "tasks",
      },
      {
        id: 5,
        title: "gantt Chart",
        icon: "/icons/gannt_chart.svg",
        path: "gantt_chart",
      },
      {
        id: 6,
        title: "Team",
        icon: "/icons/gannt_chart.svg",
        path: "team",
      },
      {
        id: 7,
        title: "settings",
        icon: "/icons/settings.svg",
        path: "settings",
      },
      {
        id: 8,
        title: "calender",
        icon: "/icons/calender.svg",
        path: "calender",
      },
      {
        id: 9,
        title: "contacts",
        icon: "/icons/contacts.svg",
        path: "contacts",
      },
      {
        id: 10,
        title: "inbox",
        icon: "/icons/inbox.svg",
        path: "inbox",
      },
      {
        id: 11,
        title: "file Manager",
        icon: "/icons/file_manager.svg",
        path: "file_manager",
      },
    ],
  },
  {
    id: 3,
    title: "Team Members",
    items: [
      { id: 1, image: "/images/user_1.png", title: "Alexandre Paiva" },
      { id: 2, image: "/images/user_2.png", title: "Thanawan Chadee" },
      { id: 3, image: "/images/user_2.png", title: "Thanawan Chadee" },
    ],
  },
];

export const counterNumericItem = [
  {
    id: 1,
    title: "DropBos",
    icon: "/images/Dropbox_Icon.svg",
    price: "368.13 Gb",
    change: "+0.73%",
    graph: "/images/Graph_1.svg",
  },
  {
    id: 1,
    title: "Amazon AWS",
    icon: "/images/Amazon.svg",
    price: "86.13 Gb",
    change: "+0.73%",
    graph: "/images/Graph_1.svg",
  },
  {
    id: 1,
    title: "Google Cloud",
    icon: "/images/Google.svg",
    price: "368.13 Gb",
    change: "+0.73%",
    graph: "/images/Graph_1.svg",
  },
];

export const lastUpdateDashboardV1 = [
  {
    id: 1,
    userImage: "/images/user_4.svg",
    username: "Username",
    time: "2 hours ago",
    desc: "Before the establishment of the Unicode Standard, there were hundreds of different systems, known encodings.",
    images: [
      "/images/dashboard_lastUpdate_v1_1.svg",
      "/images/dashboard_lastUpdate_v1_2.svg",
      "/images/dashboard_lastUpdate_v1_2.svg",
    ],
    commentNum: "20",
    likeNum: "12",
    tasks: [
      { id: 1, title: "Prepare HTML & CSS", date: "22 Oct 2019" },
      { id: 2, title: "Design new dashboard", date: "22 Oct 2019" },
      { id: 3, title: "Website design and development", date: "22 Oct 2019" },
    ],
  },
  {
    id: 2,
    userImage: "/images/user_4.svg",
    username: "Username",
    time: "2 hours ago",
    desc: "Before the establishment of the Unicode Standard, there were hundreds of different systems, known encodings.",
    commentNum: "20",
    likeNum: "12",
    tasks: [
      { id: 1, title: "Prepare HTML & CSS", date: "22 Oct 2019" },
      { id: 2, title: "Design new dashboard", date: "22 Oct 2019" },
      { id: 3, title: "Website design and development", date: "22 Oct 2019" },
    ],
  },
  {
    id: 3,
    userImage: "/images/user_4.svg",
    username: "Username",
    time: "2 hours ago",
    desc: "Before the establishment of the Unicode Standard, there were hundreds of different systems, known encodings.",
    images: [
      "/images/dashboard_lastUpdate_v1_1.svg",
      //   "/images/dashboard_lastUpdate_v1_2.svg",
    ],
    commentNum: "20",
    likeNum: "12",
  },
];

export const dashboardContactsItemsV1 = [
  {
    id: 1,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 2,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 3,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 4,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 5,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 5,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 5,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 5,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 5,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 5,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 5,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 5,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
  {
    id: 5,
    image: "/images/user_4.svg",
    title: "username",
    desc: "example@gmail.com",
  },
];

export const projectsAllItems = [
  {
    id: 0,
    category: "pending",
    image: "/public/images/Dropbox_Icon.svg",
    title: "Dropbox mobile app design",
    tasksNum: "50",
    doneNum: "40",
    commentsNum: "2",
    tagsNum: "10",
    images: [
      "/images/user_4.svg",
      "/images/user_4.svg",
      "/images/user_4.svg",
      "/images/user_4.svg",
    ],
    description:
      "When I first got into the online advertising business, I was looking for the magical combination that would put my website When I first got into the online advertising business, I was looking for the magical combination that would put my website",

    tasks: [
      {
        title: "task 1",
        id: 1,
      },
      {
        title: "task 2",
        id: 2,
      },
      {
        title: "task 3",
        id: 3,
      },
      {
        title: "task 4",
        id: 4,
      },
      {
        title: "task 5",
        id: 5,
      },
      {
        title: "task 6",
        id: 6,
      },
    ],
    attachments: ["/public/images/apple.svg", "/public/images/apple.svg"],
  },
  {
    id: 2,
    category: "done",
    image: "/public/images/dribble.svg",
    title: "Dribble mockup",
    tasksNum: "50",
    doneNum: "25",
    commentsNum: "2",
    tagsNum: "10",
    images: [
      "/images/user_4.svg",
      "/images/user_4.svg",
      "/images/user_4.svg",
      "/images/user_4.svg",
    ],
    description:
      "When I first got into the online advertising business, I was looking for the magical combination that would put my website",
  },
  {
    id: 3,
    category: "archived",
    image: "/public/images/Slack.svg",
    title: "Slack presentation for team",
    tasksNum: "50",
    doneNum: "40",
    commentsNum: "2",
    tagsNum: "10",
    images: [
      "/images/user_4.svg",
      "/images/user_4.svg",
      "/images/user_4.svg",
      "/images/user_4.svg",
    ],
  },
];

export const channelsHashtagItems = [
  { id: 1, title: "ui design", posts: "129.67K", tagNum: "20" },
  { id: 2, title: "home page", posts: "356K" },
  { id: 3, title: "ui design", posts: "36K", tagNum: "20" },
  { id: 4, title: "mobile app", posts: "36K" },
  { id: 5, title: "ui design", posts: "3K" },
];

export const teammateUpdatesItems = [
  {
    id: 1,
    title: "Homayoun Shakibaii",
    desc: "Designer",
    image: "/images/user_4.svg",
  },
  {
    id: 2,
    title: "Homayoun Shakibaii",
    desc: "Designer",
    image: "/images/user_4.svg",
  },
  {
    id: 3,
    title: "Homayoun Shakibaii",
    desc: "Designer",
    image: "/images/user_4.svg",
  },
  {
    id: 4,
    title: "Homayoun Shakibaii",
    desc: "Designer",
    image: "/images/user_4.svg",
  },
  {
    id: 5,
    title: "Homayoun Shakibaii",
    desc: "Designer",
    image: "/images/user_4.svg",
  },
];

export const kanbanTasksItems: kanbanItemType[] = [
  {
    id: 1,
    title: "making a new trend in poster",
    date: "17 Des 2022",
    userImage: "/images/user_4.svg",
    tasksNum: "50",
    doneNum: "23",
    desc: "When I first got into the online advertising business, I was looking for the magical combination that would put my website",
    attachments: ["/images/apple.svg"],
    assignedImage: ["/images/user_4.svg", "/images/user_3.svg"],
    state: "pending",
  },
  {
    id: 3,
    title: "task 3",
    date: "17 Des 2022",
    userImage: "/images/user_4.svg",
    tasksNum: "13",
    doneNum: "10",
    desc: "When I first got into the online advertising business, I was looking for the magical combination that would put my website",
    attachments: ["/images/apple.svg"],
    assignedImage: ["/images/user_4.svg", "/images/user_3.svg"],
    state: "pending",
  },
  {
    id: 2,
    title: "Manufacturing Equipment",
    date: "17 Des 2022",
    userImage: "/images/user_4.svg",
    tasksNum: "10",
    doneNum: "8",
    desc: "When I first got into the online advertising business, I was looking for the magical combination that would put my website",
    attachments: ["/images/apple.svg"],
    assignedImage: ["/images/user_4.svg", "/images/user_3.svg"],
    state: "in_progress",
  },
  {
    id: 3,
    title: "Creative Outdoor Ads",
    date: "17 Des 2022",
    userImage: "/images/user_4.svg",
    tasksNum: "34",
    doneNum: "34",
    desc: "When I first got into the online advertising business, I was looking for the magical combination that would put my website",
    attachments: [],
    assignedImage: ["/images/user_4.svg", "/images/user_3.svg"],
    state: "done",
  },
];

export const tasksItems: taskType[] = [
  {
    id: 1,
    title: "Budget and contract",
    date: "4 Aug 2022",
    userImage: "/images/user_4.svg",
    tasksNum: "23",
    doneNum: "23",
    status: "done",
  },
  {
    id: 2,
    title: "Design new dashboard",
    date: "4 Aug 2022",
    userImage: "/images/user_4.svg",
    tasksNum: "23",
    doneNum: "12",
    status: "pending",
  },
];

export const teamItems = [
  {
    id: 1,
    username: "username 1",
    email: "example.com",
    userImage: "/images/user_4.svg",
  },
  {
    id: 2,
    username: "username 2",
    email: "example.com",
    userImage: "/images/user_4.svg",
  },
];

export const contactItems = [
  {
    id: 1,
    username: "username 1",
    email: "example.com",
    phoneNumber: "09874839849",
    role: "customers",
    userImage: "/images/user_4.svg",
    bio: "Happiness is not something readymade.It comes from your own actions.",
    tasks: "296",
    newTaskBadge: "4",
    followers: "18",
    followersBadge: "9",
    totalBudget: "234.24",
    hourlyRate: "34",
    skills: [
      { title: "Mobile App" },
      { title: "User Experience" },
      { title: "Interface Design" },
      { title: "Entrepreneur" },
      { title: "Html" },
      { title: "Founder" },
      { title: "Development" },
      { title: "Marketing" },
      { title: "Business" },
    ],
    work_experience: [
      {
        image: "/images/dribble.svg",
        title: "Crisis Intervention Specialist",
        location: "London",
        company: "Dribble inc",
        desc: "Minimum 3 shifts a week Monday - Friday with the ability to work an 8 to 9 hour time each week between the hours of 7 A.M. - 7 P.M.",
        startTime: "2001",
        endTime: "2010",
      },
      {
        image: "/images/Google.svg",
        title: "Virtual Scheduler",
        location: "London",
        company: "Google inc",
        desc: "Lines for Life also offers a great benefits package valued at over $9,500 that includes full coverage for employee health, dental, vision, short",
        startTime: "2009",
        endTime: "2010",
      },
    ],
  },
  {
    id: 2,
    username: "username 2",
    email: "example.com",
    phoneNumber: "09874839849",
    role: "teammates",
    userImage: "/images/user_4.svg",
  },
];

export const inboxChatItem = [
  {
    id: 1,
    userImage: "/images/user_4.svg",
    username: "username 1 ",
    title: "Leaving Fingerprints on the iPhone",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
  {
    id: 2,
    userImage: "/images/user_3.svg",
    username: "username 2",
    title: "Microsoft Looks to Regain",
    desc: "How To Write Better Advertising Graphic designers always",
    time: "11:30AM",
  },
];

export const fileManagerItems = [
  {
    id: 1,
    title: "Recent uploads",
    role: "customer",
    files: [
      {
        id: 1,
        title: "UI Design.sketch",
        size: "12 mb",
        date: "14 Oct 2022",
        images: [
          "/images/user_4.svg",
          "/images/user_4.svg",
          "/images/user_4.svg",
        ],
        uploadedBy: "username 3",
        uploadedByImage: "/images/user_3.svg",
        dateUploaded: "10/18/2020, 9:44 PM",
        lastModified: "10/18/2020, 9:47 PM",
        extension: ".sketch",
        sharedWith: "Public access",
        publicLink: "https://whiteui.store/saasuikit",
        category: "documents",
      },
      {
        id: 2,
        title: "Logo Vector.ai",
        size: "73.3 mb",
        date: "12 Oct 2022",
        images: [
          "/images/user_4.svg",
          "/images/user_3.svg",
          "/images/user_4.svg",
        ],
        uploadedBy: "username 2",
        uploadedByImage: "/images/user_4.svg",
        dateUploaded: "10/12/2020, 9:44 PM",
        lastModified: "10/14/2020, 9:47 PM",
        extension: ".sketch",
        sharedWith: "Public access",
        publicLink: "https://whiteui.store/saasuikit",
        category: "images",
      },
      {
        id: 3,
        title: "Wireframe for team.figma",
        size: "73.3 mb",
        date: "12 Oct 2022",
        images: [
          "/images/user_3.svg",
          "/images/user_3.svg",
          "/images/user_4.svg",
        ],
        uploadedBy: "username 3",
        uploadedByImage: "/images/user_3.svg",
        dateUploaded: "10/2/2020, 9:44 PM",
        lastModified: "19/14/2020, 9:47 PM",
        extension: ".sketch",
        sharedWith: "Public access",
        publicLink: "https://whiteui.store/saasuikit",
        category: "archives",
      },
    ],
  },
  {
    id: 2,
    title: "Screenshots",
    role: "teammate",
    files: [
      {
        id: 1,
        title: "Wireframe for team.figma",
        size: "12 mb",
        date: "14 Oct 2022",
        images: [
          "/images/user_4.svg",
          "/images/user_4.svg",
          "/images/user_4.svg",
        ],
        uploadedBy: "username 3",
        uploadedByImage: "/images/user_3.svg",
        dateUploaded: "10/18/2020, 9:44 PM",
        lastModified: "10/18/2020, 9:47 PM",
        extension: ".sketch",
        sharedWith: "Public access",
        publicLink: "https://whiteui.store/saasuikit",
        category: "documents",
      },
      {
        id: 2,
        title: "Logo Vector.ai",
        size: "73.3 mb",
        date: "12 Oct 2022",
        images: [
          "/images/user_4.svg",
          "/images/user_3.svg",
          "/images/user_4.svg",
        ],
        uploadedBy: "username 2",
        uploadedByImage: "/images/user_4.svg",
        dateUploaded: "10/12/2020, 9:44 PM",
        lastModified: "10/14/2020, 9:47 PM",
        extension: ".sketch",
        sharedWith: "Public access",
        publicLink: "https://whiteui.store/saasuikit",
        category: "images",
      },
      {
        id: 3,
        title: "Wireframe for team.figma",
        size: "73.3 mb",
        date: "12 Oct 2022",
        images: [
          "/images/user_3.svg",
          "/images/user_3.svg",
          "/images/user_4.svg",
        ],
        uploadedBy: "username 3",
        uploadedByImage: "/images/user_3.svg",
        dateUploaded: "10/2/2020, 9:44 PM",
        lastModified: "19/14/2020, 9:47 PM",
        extension: ".sketch",
        sharedWith: "Public access",
        publicLink: "https://whiteui.store/saasuikit",
        category: "documents",
      },
    ],
  },
];

export const calenderTasksItem: any[] = [
  {
    date: "2024-07-05",
    tasks: [
      { id: 1, task: "meeting" },
      { id: 2, task: "call" },
      { id: 2, task: "call" },
    ],
  },
  {
    date: "2024-07-18",
    tasks: [{ id: 1, task: "meeting", time: "10:00" }],
  },
  {
    date: "2024-07-31",
    tasks: [
      { id: 1, task: "meeting", time: "13:00" },
      { id: 2, task: "call", time: "09:30" },
    ],
  },
  {
    date: "2024-07-30",
    tasks: [{ id: 1, task: "meeting", time: "10:00" }],
  },
  {
    date: "2024-08-24",
    tasks: [{ id: 1, task: "meeting", time: "10:00" }],
  },
];

export const calenderWeekTime = [
  { time: "07:00" },
  { time: "07:30" },
  { time: "08:00" },
  { time: "08:30" },
  { time: "09:00" },
  { time: "09:30" },
  { time: "10:00" },
  { time: "10:30" },
  { time: "11:00" },
  { time: "11:30" },
  { time: "12:00" },
  { time: "12:30" },
  { time: "13:00" },
  { time: "13:30" },
  { time: "14:00" },
];
